on: push

jobs:
  export_game:
    runs-on: ubuntu-latest
    name: Export Game Job
    env:
      GODOT_ANDROID_KEYSTORE_DEBUG_PATH: /home/runner/work/godot-export/godot-export/examples/project-godot-4/debug.keystore
      GODOT_ANDROID_KEYSTORE_DEBUG_USER: androiddebugkey
      GODOT_ANDROID_KEYSTORE_DEBUG_PASSWORD: android
    steps:
      - name: checkout
        uses: actions/checkout@v3.3.0

      - name: install wine
        id: wine_install
        run: |
          sudo apt install wine64
          echo "WINE_PATH=$(which wine64)" >> $GITHUB_OUTPUT

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # - name: Setup Godot Editor Settings
      #   run: |
      #       mkdir -p ~/.config/godot
      #       cp ./examples/project-godot-4/editor_settings-4.tres ~/.config/godot/editor_settings-4.tres
      #       cp ./examples/project-godot-4/debug.keystore ~/.config/godot/debug.keystore

      - name: export game
        id: export
        uses: firebelley/godot-export@v5.2.0
        with:
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.2.2/Godot_v4.2.2-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.2.2/Godot_v4.2.2-stable_export_templates.tpz
          relative_project_path: ./examples/project-godot-4
          relative_export_path: ./my/build/destination
          archive_output: true
          export_debug: true
          cache: true
          wine_path: ${{ steps.wine_install.outputs.WINE_PATH }}

      - name: create release
        uses: ncipollo/release-action@v1.11.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
          tag: ${{ github.ref_name }}-${{ github.sha }}
          artifacts: ${{ steps.export.outputs.archive_directory }}/*
